Makeup layout
0603anton/admin-panel-makeup pull request #1
Opened 2022-01-19 19:42 UTC by 0603anton

Здание выполнено с использованием flexbox. "резина" по ширине достигается за счёт родных свойств flexbox, которые позволяют flex-item  тянуться и сужаться(width:auto и flex-shrink:1), они установлены по умолчанию.

"Резина" по высоте за счёт свойства flex-direction, здесь мы меняем положение основной оси flex-контейнера и задаём ему высоту 100%, а дочерним элементам включаем flex-grow. Что позволяет элементу автоматически тянуться на любую высоту. 

При выполнении использовал статью: https://css-tricks.com/boxes-fill-height-dont-squish/

2022-01-20 06:40 UTC, 0603anton commented on style.css
> -  flex: 1;
Убрал flex-grow т.к. сначала сделал резину на любые размеры без ограничений на максимальные, как в макете

2022-01-21 17:21 UTC, Muslik requested changes

2022-01-21 17:21 UTC, Muslik commented on index.html
> +        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur, quisquam dolore asperiores sequi minima
На макете этого нет

2022-01-21 17:21 UTC, Muslik commented on index.html
> +      <div class="filter__elem filter__elem_sm filter__elem_right-elem"></div>
right_elem не может быть модификатором. Нужно какой то смысловое название как выше lg и sm (это про размеры). Либо обойтись без модификаторов

2022-01-21 17:21 UTC, Muslik commented on index.html
> +    <div class="filter main-content__margin">
main-content__margin - что такое margin? Это отступ. Почему это присутствует в названии класса? Выше такая же ошибка. В названии класса должно быть смысловое название блока. header, searchbar, table.

Варианты: margin, flex, border - это css свойства, но никак не названия классов

2022-01-21 17:21 UTC, Muslik commented on style.css
> +  /* min-height: 100%; */
Лишние комменты удалить

2022-01-21 17:21 UTC, Muslik commented on index.html
> +<!DOCTYPE html>
По макету контенте должен занимать всю ширину с отступами по бокам. У вас не так. Таблица должна занимать все оставшееся место на экране, поэтому футер таблицы должен быть в нижней части.

2022-01-21 17:21 UTC, Muslik commented on index.html
> +<!DOCTYPE html>
У среднего блока border по толщине больше должен быть.

Также у среднего блока вы делаете отступы сверху снизу (слева для первого блока, справа для последнего) для каждого блока индивидуально. Это неправильный подход. Используйте padding у родителя и тогда все блоки будут располагаться с необходимыми отступами сверху и снизу

2022-01-21 17:21 UTC, Muslik commented on style.css
> +  height: 51.2rem;
Тут не должно быть фиксированной высоты

2022-01-21 17:21 UTC, Muslik commented on style.css
> +  position: sticky;
Бесполезное свойство

2022-01-22 18:56 UTC, 0603anton commented on index.html
> +        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur, quisquam dolore asperiores sequi minima
Убрал контент. Оставил в HTML структуре блок с необходимым свойством, чтобы макет правильно себя вёл с контентом.

2022-01-22 18:56 UTC, 0603anton commented on index.html
> +      <div class="filter__elem filter__elem_sm filter__elem_right-elem"></div>
Убрал модификатор, решил по другому. Разбил элементы на 2 группы а между ними justify-content:space between

2022-01-22 18:56 UTC, 0603anton commented on index.html
> +    <div class="filter main-content__margin">
исправил наименование элементов согласно BEM

2022-01-22 18:56 UTC, 0603anton commented on style.css
> +  /* min-height: 100%; */
сделано

2022-01-22 18:57 UTC, 0603anton commented on index.html
> +<!DOCTYPE html>
Исправил:
1) Ширина макета тоже резиновая, не ограничена никак
2) Средний блок поправил border на 2px
3) Добавил padding для родителя

2022-01-22 18:57 UTC, 0603anton commented on style.css
> +  height: 51.2rem;
Убрал фикс значения

2022-01-22 18:57 UTC, 0603anton commented on style.css
> +  position: sticky;
Если тут имелось ввиду position sticky тоже убрал. Решил проблему благодаря макету который Сергей на уроке скидывал и писал про него в телеграмме и вот тут второе по популярности решение https://stackoverflow.com/questions/21515042/scrolling-a-flexbox-with-overflowing-content. Теперь макет с контентом ведёт себя так же как и на вашем видео.

2022-01-23 13:44 UTC, Muslik commented on index.html
> +        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur, quisquam dolore asperiores sequi minima
Можно его тоже удалить. Все будет ок

2022-01-23 13:45 UTC, Muslik approved these changes

2022-01-23 15:50 UTC, merged